### ISSUE TITLE
Would be nice to be credited for original authorship

### ISSUE THREAD

**Issue by jwiegley** [strake/reg-alloc.hs#1]
Hi! I'm entirely in support of you copying code from linearscan and branching out into your own version of it, but the copyright requires that you copy both the license and author attribution into the new variant of the code. Thank you, and long live the spirit of academic collaboration.

**Comment by strake** [comment]
Oh, sorry! I moved the `RegAlloc.Types` module into its [own package](https://github.com/strake/reg-alloc-types.hs), which notes its original authorship in the module file itself, but forgot to modify this one to depend on it. I have since [done so](https://github.com/strake/reg-alloc.hs/commit/03e3ef19b98d0aaf62383100c489dfad30973943).

I also [added](https://github.com/strake/reg-alloc.hs/commit/6d63959f5ad27b7c9be6c218252dda47ffaf1812) a comment to the `RegAlloc` signature.

(The LICENSE file already noted you as an earlier copyright holder, but that's not quite the same as an author attribution, so you make a fair point nonetheless.)

I hope this clears up your concern.

**Comment by jwiegley** [comment]
Thank you so much, @strake! Best of luck.
